#:schema node_modules/wrangler/config-schema.json
name = "wirespec-serve"
main = "src/index.ts"
compatibility_date = "2024-04-19"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
 binding = "WIRESPEC"
 id = "c36ffb347005444a9bb161e676b79e2c"

routes = [
	{ pattern = "serve.wirespec.io", custom_domain = true },
	{ pattern = "*.serve.wirespec.io", custom_domain = true }
]
